# build from the official Nginx image
FROM nginx

# Capture the build domain input argument and create an environment variable from it
ARG build_domain
ENV DOMAIN $build_domain

# establish where Nginx should look for files
ENV WEB_ROOT /home/maverick/Public/

# Set our working directory inside the image
WORKDIR $WEB_ROOT

# copy our Nginx config template
COPY ./nginx/server.conf /tmp/docker_example.nginx

# substitute variable references in the Nginx config template for real values from the environment
# put the final config in its place
RUN envsubst '$DOMAIN:$WEB_ROOT' < /tmp/docker_example.nginx > /etc/nginx/conf.d/default.conf

# copy over the script that is run by the container
COPY ./nginx/web_cmd.sh /tmp/
RUN ["chmod", "+x", "/tmp/web_cmd.sh"]

# Define the script we want run once the container boots
# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
CMD [ "/tmp/web_cmd.sh" ]
