title: jsorge.net
description: Christian, husband, dad, developer, batman aficianado
url: https://jsorge.net
metaDescription: By Jared Sorge.
batchSize: 10
ssl:
  contactEmail: jared@jsorge.net
feedSize: 50
sitesToPing:
  - https://micro.blog/ping?url=https%3A%2F%2Fjsorge.net%2Ffeed.json
