metaDescription: I'm Jared Sorge and this is my website. I'm a Christian, husband, dad, developer, and batman aficianado.
title: jsorge.net
description: The staging site for jsorge.net
url: https://sorge.me
batchSize: 5
