server {
    listen 80;
    server_name $DOMAIN;

    root $WEB_ROOT;

    try_files $uri @proxy;

    location @proxy {
        proxy_pass http://maverick:8080;
        proxy_pass_header Server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 3s;
        proxy_read_timeout 10s;
    }

    # Health check endpoint for monitoring
    location /health {
        access_log off;
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }
}
