version: "3.3"
services:
  maverick:
    image: jsorge/maverick:0d02851
    restart: on-failure
    volumes:
      - ../Public:/app/Public
      - ../Resources:/app/Resources
      - ../SiteConfig.yml:/app/SiteConfig.yml
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile-nginx
      args:
        build_domain: {CONFIG_DOMAIN}
    environment:
      CA_SSL: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../Public:/home/maverick/Public
      - ./nginx/ssl:/var/www/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - maverick
