name: Publish to Server

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
    - name: Add remote to known_hosts
      run: |
        #!/usr/bin/env bash
        # fail if any commands fails
        set -e
        # debug log
        set -x

        for ip in $(dig @8.8.8.8 jsorge.net +short); do ssh-keyscan jsorge.net,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.JSN_PRIVATE_KEY }}
    - name: Push to Remote
      run: |
        #!/bin/bash
        ssh jsorge@jsorge.net 'cd /var/www/jsorge.net/; git fetch && git pull'
