name: Publish to Server

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.JSN_PRIVATE_KEY }}
    - name: Push to Remote
      run: |
        #!/bin/bash
        ssh -o "StrictHostKeyChecking=no" jsorge@jsorge.net 'cd /var/www/jsorge.net/; git fetch && git pull'
